import { StyleSheet, Dimensions, Platform } from 'react-native';
const { height: SCREEN_HEIGHT } = Dimensions.get('window');
export const loginColors = { primary: '#EBD600', white: '#FFFFFF', black: '#1A1A1A', headerBg: '#121212', grayWarm: '#6B6660', grayText: '#8A8A8A', grayLight: '#E5E5E5', danger: '#D64545', pillBg: 'rgba(255, 255, 255, 0.12)' } as const;

/** Estilos centralizados. Uso: app/login.tsx. */
export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: loginColors.white,
  },
  flex: {
    flex: 1,
  },
  container: {
    flexGrow: 1,
    backgroundColor: loginColors.white,
  },
  blackBand: {
    height: SCREEN_HEIGHT * 0.44,
    backgroundColor: loginColors.headerBg,
    position: 'relative',
    overflow: 'hidden',
  },
  // Formas curvas de la cabecera
  curve1: {
    width: 320,
    height: 320,
    borderRadius: 160,
    backgroundColor: 'rgba(255, 255, 255, 0.03)',
    position: 'absolute',
    top: -120,
    right: -80,
  },
  curve2: {
    width: 260,
    height: 260,
    borderRadius: 130,
    backgroundColor: 'rgba(255, 255, 255, 0.02)',
    position: 'absolute',
    top: -40,
    left: -100,
  },
  curve3: {
    width: 180,
    height: 180,
    borderRadius: 90,
    backgroundColor: 'rgba(255, 255, 255, 0.015)',
    position: 'absolute',
    bottom: -40,
    right: -30,
  },
  // Contenedor del grupo de logo y brillo para animar escala en conjunto
  logoGroupContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    width: 320,
    height: 120,
    alignSelf: 'center',
    marginTop: Platform.OS === 'ios' ? 45 : 55,
    position: 'relative',
  },
  // Contenedor del brillo difuminado
  glowWrapper: {
    position: 'absolute',
    width: 380,
    height: 380,
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 1,
  },
  glowImage: {
    width: '100%',
    height: '100%',
    tintColor: '#EBD600', // Convierte el brillo azul a amarillo Campo Maq
  },
  logo: {
    width: 210,
    height: 210 / 3.85,
    zIndex: 2,
  },
  heroTextContainer: {
    position: 'absolute',
    left: 24,
    bottom: 30,
    right: 24,
  },
  subtitleLeft: {
    fontFamily: 'Barlow_700Bold',
    fontSize: 12,
    color: 'rgba(255, 255, 255, 0.6)',
    letterSpacing: 1.5,
    marginBottom: 6,
  },
  titleLeft: {
    fontFamily: 'Barlow_700Bold',
    fontSize: 28,
    color: loginColors.white,
    lineHeight: 34,
    fontWeight: '800',
  },
  branchPill: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'flex-start',
    backgroundColor: loginColors.pillBg,
    borderRadius: 20,
    paddingHorizontal: 12,
    paddingVertical: 6,
    marginTop: 14,
    gap: 6,
  },
  branchText: {
    fontFamily: 'Barlow_600SemiBold',
    fontSize: 12,
    color: loginColors.white,
  },
  formContainer: {
    paddingHorizontal: 24,
    paddingTop: 28,
    backgroundColor: loginColors.white,
  },
  fieldLabel: {
    fontFamily: 'Barlow_700Bold',
    fontSize: 11,
    color: loginColors.grayWarm,
    letterSpacing: 0.8,
    textTransform: 'uppercase',
    marginBottom: 8,
  },
  inputBox: {
    flexDirection: 'row',
    alignItems: 'center',
    height: 54,
    borderRadius: 12,
    borderWidth: 1.5,
    borderColor: loginColors.grayLight,
    backgroundColor: loginColors.white,
    paddingHorizontal: 16,
    marginBottom: 20,
  },
  inputBoxFocused: {
    borderWidth: 2,
    borderColor: loginColors.primary,
    // Efecto premium de sombra leve del color de marca
    shadowColor: loginColors.primary,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
  },
  textInput: {
    flex: 1,
    height: '100%',
    paddingLeft: 12,
    fontSize: 14,
    color: loginColors.black,
    fontFamily: 'Barlow_500Medium',
    backgroundColor: loginColors.white,
  },
  eyeButton: {
    padding: 6,
    marginRight: -4,
  },
  rememberRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 28,
  },
  checkboxContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  checkbox: {
    width: 18,
    height: 18,
    borderRadius: 4,
    borderWidth: 1.5,
    borderColor: loginColors.primary,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: loginColors.white,
  },
  checkboxChecked: {
    borderColor: loginColors.primary,
    backgroundColor: loginColors.primary,
  },
  forgotText: {
    fontFamily: 'Barlow_600SemiBold',
    fontSize: 13,
    color: loginColors.black,
    textDecorationLine: 'underline',
  },
  checkboxText: {
    fontFamily: 'Barlow_500Medium',
    fontSize: 13,
    color: loginColors.grayWarm,
  },
  errorBox: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: '#FFF2F2',
    borderRadius: 12,
    padding: 12,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: '#FFE0E0',
  },
  errorText: {
    fontFamily: 'Barlow_500Medium',
    fontSize: 12,
    color: loginColors.danger,
    flex: 1,
  },
  submitButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    height: 54,
    borderRadius: 12,
    backgroundColor: loginColors.primary,
    paddingVertical: 16,
    // Sombra premium del color de marca en iOS y Android
    shadowColor: loginColors.primary,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.35,
    shadowRadius: 10,
    elevation: 5,
  },
  submitButtonDisabled: {
    opacity: 0.5,
    shadowOpacity: 0,
    elevation: 0,
  },
  submitButtonPressed: {
    opacity: 0.85,
  },
  submitButtonText: {
    fontFamily: 'Barlow_700Bold',
    fontSize: 15,
    color: loginColors.black,
    fontWeight: '700',
    letterSpacing: 0.5,
  },
  separatorContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: 24,
  },
  separatorLine: {
    flex: 1,
    height: 1,
    backgroundColor: loginColors.grayLight,
  },
  separatorText: {
    fontFamily: 'Barlow_500Medium',
    fontSize: 13,
    color: loginColors.grayText,
    marginHorizontal: 12,
  },
  qrButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    height: 54,
    borderRadius: 12,
    backgroundColor: loginColors.white,
    borderWidth: 1,
    borderColor: loginColors.grayLight,
    gap: 8,
  },
  qrButtonPressed: {
    backgroundColor: '#F9F9F9',
  },
  qrButtonText: {
    fontFamily: 'Barlow_600SemiBold',
    fontSize: 14,
    color: loginColors.black,
  },
  footerContainer: {
    paddingVertical: 32,
    justifyContent: 'center',
    alignItems: 'center',
  },
  footerText: {
    fontFamily: 'Barlow_500Medium',
    fontSize: 11,
    color: loginColors.grayText,
  },
});
