import { StyleSheet } from 'react-native';
import { colors } from '@/theme/colors';
import { radius, spacing } from '@/theme/spacing';

/**
 * Estilos para el componente UserAvatar (botón de cabecera y modal desplegable al centro).
 */
export const styles = StyleSheet.create({
  // --- Botón Trigger en Cabecera ---
  triggerButton: {
    borderRadius: radius.pill,
    backgroundColor: '#1A1A1A',
    borderWidth: 2,
    borderColor: colors.primary,
    justifyContent: 'center',
    alignItems: 'center',
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 4,
    elevation: 3,
  },
  triggerImage: {
    width: '100%',
    height: '100%',
  },
  triggerText: {
    fontSize: 15,
    fontWeight: '700',
    color: colors.primary,
    letterSpacing: 0.5,
  },

  // --- Modal Overlay y Animación al Centro ---
  modalOverlay: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: spacing.md,
  },
  backdrop: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(15, 15, 15, 0.65)',
  },
  backdropPressable: {
    flex: 1,
  },
  dialogCard: {
    width: '100%',
    maxWidth: 340,
    backgroundColor: colors.surface,
    borderRadius: 24,
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.md,
    paddingBottom: spacing.lg,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#ECECEC',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.25,
    shadowRadius: 20,
    elevation: 12,
  },

  // --- Cabecera del Card ---
  cardTopRow: {
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: spacing.xs,
  },
  cardLabel: {
    fontSize: 11,
    fontWeight: '700',
    color: colors.gray,
    letterSpacing: 1,
    textTransform: 'uppercase',
  },
  closeButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#F4F4F5',
    justifyContent: 'center',
    alignItems: 'center',
  },

  // --- Avatar Grande Central ---
  largeAvatarWrapper: {
    position: 'relative',
    marginTop: spacing.xs,
    marginBottom: spacing.md,
  },
  largeAvatarContainer: {
    width: 108,
    height: 108,
    borderRadius: 54,
    borderWidth: 3.5,
    borderColor: colors.primary,
    backgroundColor: '#1A1A1A',
    justifyContent: 'center',
    alignItems: 'center',
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.18,
    shadowRadius: 8,
    elevation: 6,
  },
  largeAvatarImage: {
    width: '100%',
    height: '100%',
  },
  largeAvatarText: {
    fontSize: 36,
    fontWeight: '800',
    color: colors.primary,
    letterSpacing: 1,
  },
  cameraBadge: {
    position: 'absolute',
    bottom: 0,
    right: 0,
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: colors.primary,
    borderWidth: 2.5,
    borderColor: colors.surface,
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 4,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 3,
  },

  // --- Información de Usuario ---
  userName: {
    fontSize: 20,
    fontWeight: '800',
    color: colors.black,
    textAlign: 'center',
    marginBottom: 2,
  },
  userEmail: {
    fontSize: 13,
    fontWeight: '400',
    color: colors.grayDark,
    textAlign: 'center',
    marginBottom: spacing.sm,
  },
  roleBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    backgroundColor: '#FFFBE6',
    borderWidth: 1,
    borderColor: '#FFE58F',
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: radius.pill,
    marginBottom: spacing.md,
  },
  roleBadgeText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#874D00',
  },

  // --- Acciones y Botón de Salir ---
  actionsContainer: {
    width: '100%',
    gap: spacing.sm,
    marginTop: spacing.xs,
  },
  changePhotoButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.sm,
    height: 42,
    borderRadius: radius.md,
    backgroundColor: '#F7F7F8',
    borderWidth: 1,
    borderColor: colors.border,
  },
  changePhotoText: {
    fontSize: 14,
    fontWeight: '600',
    color: colors.black,
  },
  divider: {
    width: '100%',
    height: 1,
    backgroundColor: '#F0F0F0',
    marginVertical: 4,
  },
  logoutButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.sm,
    height: 46,
    borderRadius: radius.md,
    backgroundColor: '#FFF1F0',
    borderWidth: 1,
    borderColor: '#FFCCC7',
  },
  logoutButtonText: {
    fontSize: 14,
    fontWeight: '700',
    color: colors.danger,
  },
  // --- Confirmación en el mismo elemento ---
  confirmLogoutContainer: {
    width: '100%',
    backgroundColor: '#FFF1F0',
    borderWidth: 1,
    borderColor: '#FFCCC7',
    borderRadius: radius.md,
    padding: spacing.sm,
    gap: spacing.sm,
    alignItems: 'center',
  },
  confirmLogoutText: {
    fontSize: 13,
    fontWeight: '700',
    color: colors.black,
    textAlign: 'center',
  },
  confirmButtonsRow: {
    flexDirection: 'row',
    width: '100%',
    gap: spacing.sm,
  },
  cancelLogoutButton: {
    flex: 1,
    height: 38,
    borderRadius: radius.sm,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: '#D9D9D9',
    justifyContent: 'center',
    alignItems: 'center',
  },
  cancelLogoutText: {
    fontSize: 13,
    fontWeight: '600',
    color: colors.grayDark,
  },
  confirmLogoutButton: {
    flex: 1,
    height: 38,
    borderRadius: radius.sm,
    backgroundColor: colors.danger,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 6,
  },
  confirmLogoutButtonText: {
    fontSize: 13,
    fontWeight: '700',
    color: '#FFFFFF',
  },
});
