import { StyleSheet } from 'react-native';
import { colors } from '@/theme/colors';
import { radius, spacing } from '@/theme/spacing';
import { typography } from '@/theme/typography';

/** Estilos centralizados. Uso: src/features/clients/components/ClientDetail.tsx. */
export const styles = StyleSheet.create({
  container: { gap: spacing.md },
  profileHeader: { flexDirection: 'row', alignItems: 'center', gap: spacing.md },
  profileText: { flex: 1, gap: 2 },
  name: { ...typography.title, color: colors.black, fontSize: 20, fontWeight: '700' },
  ruc: { ...typography.body, color: colors.grayDark, fontSize: 13 },
  locationRow: { flexDirection: 'row', alignItems: 'center', gap: 4, marginTop: 2 },
  location: { ...typography.caption, color: colors.grayDark, fontSize: 12, fontWeight: '500' },
  actions: { flexDirection: 'row', gap: spacing.sm },
  actionButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.xs,
    paddingVertical: spacing.sm,
    backgroundColor: '#FAFAFA',
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: '#EAEAEA',
  },
  actionLabel: { ...typography.caption, fontWeight: '600', color: colors.black },
  metrics: { flexDirection: 'row', gap: spacing.sm },
  metricCard: {
    flex: 1,
    minHeight: 74,
    justifyContent: 'center',
    backgroundColor: colors.surface,
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: colors.border,
    padding: spacing.sm,
  },
  metricCardScore: {
    backgroundColor: colors.black,
    borderColor: colors.black,
  },
  metricLabel: {
    ...typography.caption,
    color: colors.gray,
    fontWeight: '600',
    marginBottom: 4,
  },
  metricLabelScore: {
    color: colors.grayLight,
  },
  metricValue: {
    fontSize: 18,
    fontWeight: '700',
    color: colors.black,
  },
  metricValueScore: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
  },
  scoreText: {
    fontSize: 18,
    fontWeight: '700',
    color: colors.surface,
  },
  tabs: { flexDirection: 'row', borderBottomWidth: 1, borderBottomColor: colors.border },
  tabButton: { flex: 1, alignItems: 'center', paddingVertical: spacing.sm, borderBottomWidth: 3, borderBottomColor: 'transparent' },
  tabButtonActive: { borderBottomColor: colors.primary },
  tabLabel: { ...typography.body, color: colors.gray },
  tabLabelActive: { color: colors.black, fontWeight: '700' },
  section: { gap: spacing.sm },
  emptyText: { ...typography.body, color: colors.grayDark, textAlign: 'center', paddingVertical: spacing.lg },
  invoiceCard: {
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md,
    padding: spacing.md,
    gap: spacing.xs,
  },
  invoiceTopRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 2 },
  invoiceHeader: { ...typography.caption, color: colors.gray, fontWeight: '500' },
  invoiceName: { fontSize: 16, color: colors.black, fontWeight: '600' },
  invoiceMeta: { ...typography.caption, color: colors.grayDark },
  dashedLine: {
    height: 1,
    borderWidth: 1,
    borderColor: '#E5E5E5',
    borderStyle: 'dashed',
    marginVertical: spacing.sm,
  },
  invoiceBottomRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  invoiceTotal: { fontSize: 18, color: colors.black, fontWeight: '700' },
  detailLink: { flexDirection: 'row', alignItems: 'center', gap: 2 },
  detailLinkText: { ...typography.caption, color: colors.primaryDark, fontWeight: '600' },
  dataCard: { backgroundColor: colors.surface, borderRadius: radius.md, borderWidth: 1, borderColor: colors.border, paddingHorizontal: spacing.md },
  dataRow: { paddingVertical: spacing.sm, borderBottomWidth: 1, borderBottomColor: colors.border, gap: 2 },
  dataLabel: { ...typography.caption, color: colors.gray },
  dataValue: { ...typography.body, color: colors.black },
  noteCard: { flexDirection: 'row', gap: spacing.sm, backgroundColor: colors.surface, borderRadius: radius.md, borderWidth: 1, borderColor: colors.border, padding: spacing.md },
  noteText: { ...typography.body, color: colors.grayDark, flex: 1 },
  pressed: { opacity: 0.7 },
  disabled: { opacity: 0.45 },
});
